PROV_NET:
  hosts:
    SWT010:
      ansible_host: 192.168.1.10
    SWT011:
      ansible_host: 192.168.1.11
    SWT012:
      ansible_host: 192.168.1.12
    SWT020:
      ansible_host: 192.168.1.20
    SWT021:
      ansible_host: 192.168.1.21
  vars:
    ansible_connection: network_cli
    ansible_network_os: arubanetworks.aoscx.aoscx
...