---
FIRMWARE_UPDATE:
  hosts:
    SWT010:
      ansible_host: 192.168.1.10
      switch_model: 6100
    SWT011:
      ansible_host: 192.168.1.11
      switch_model: 6300
    SWT012:
      ansible_host: 192.168.1.12
      switch_model: 6100
    SWT013:
      ansible_host: 192.168.1.13
      switch_model: 6300
    SWT014:
      ansible_host: 192.168.1.14
      switch_model: 6300
    SWT015:
      ansible_host: 192.168.1.15
      switch_model: 6300
    SWT016:
      ansible_host: 192.168.1.16
      switch_model: 6300
  vars:
    ansible_connection: network_cli
    ansible_network_os: arubanetworks.aoscx.aoscx
MAIN:
  hosts:
    SWT010:
      ansible_host: 192.168.1.10
      config_file: /home/ax3413/ansible/ansible_playbooks/refresh/config_files/generated_configs/SWT010_base_config.ios
    SWT011:
      ansible_host: 192.168.1.11
      config_file: /home/ax3413/ansible/ansible_playbooks/refresh/config_files/generated_configs/SWT011_base_config.ios
    SWT012:
      ansible_host: 192.168.1.12
      config_file: /home/ax3413/ansible/ansible_playbooks/refresh/config_files/generated_configs/SWT012_base_config.ios
    SWT013:
      ansible_host: 192.168.1.13
      config_file: /home/ax3413/ansible/ansible_playbooks/refresh/config_files/generated_configs/SWT013_base_config.ios
    SWT014:
      ansible_host: 192.168.1.14
      config_file: /home/ax3413/ansible/ansible_playbooks/refresh/config_files/generated_configs/SWT014_base_config.ios
  vars:
    ansible_connection: network_cli
    ansible_network_os: arubanetworks.aoscx.aoscx
VSF_DEVICES:
  children:
    conductors:
      hosts:
        192.168.1.14:
          link_1: 1/1/51
          link_2: 1/1/52
          member_number: '1'
          member_type: conductor
          secondary_member: '3'
          stack_number: '1'
    members:
      hosts:
        192.168.1.15:
          link_1: 1/1/51
          link_2: 1/1/52
          member_number: '2'
          member_type: member
          secondary_member: ''
          stack_number: '1'
        192.168.1.16:
          link_1: 1/1/51
          link_2: 1/1/52
          member_number: '3'
          member_type: standby
          secondary_member: ''
          stack_number: '1'
  vars:
    ansible_connection: network_cli
    ansible_network_os: arubanetworks.aoscx.aoscx
...
